import concat from 'lodash/concat';
import debounce from 'lodash/debounce';
import filter from 'lodash/filter';
import find from 'lodash/find';
import findIndex from 'lodash/findIndex';
import forEach from 'lodash/forEach';
import forOwn from 'lodash/forOwn';
import get from 'lodash/get';
import groupBy from 'lodash/groupBy';
import includes from 'lodash/includes';
import indexOf from 'lodash/indexOf';
import isString from 'lodash/isString';
import map from 'lodash/map';
import merge from 'lodash/merge';
import orderBy from 'lodash/orderBy';
import set from 'lodash/set';
import sortBy from 'lodash/sortBy';
import sumBy from 'lodash/sumBy';
import take from 'lodash/take';
import uniq from 'lodash/uniq';

export const lodashGet = get;
export const lodashMap = map;
export const lodashFilter = filter;
export const lodashFind = find;
export const lodashFindIndex = findIndex;
export const lodashOrderBy = orderBy;
export const lodashSortBy = sortBy;
export const lodashIncludes = includes;
export const lodashIsString = isString;
export const lodashForOwn = forOwn;
export const lodashSumBy = sumBy;
export const lodashGroupBy = groupBy;
export const lodashConcat = concat;
export const lodashIndexOf = indexOf;
export const lodashUniq = uniq;
export const lodashDebounce = debounce;
export const lodashMerge = merge;
export const lodashForEach = forEach;
export const lodashSet = set;
export const lodashTake = take;
